Repository sprint6-part2/fandom-k, pull requests merged in 2024-05, with the labels that each got.

#15 ✨ Feat: 프로필 사진 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/Check.jsx
  src/assets/icons/ProfileX.jsx
  src/components/Profile/index.jsx
  src/components/Profile/styles.module.scss
  src/pages/TestPage/index.jsx
  src/styles/index.scss
Labels: ✨ Feat

#22 ✨ Feat: 프로필 사진 컴포넌트 구현
  src/assets/icons/Check.jsx
  src/assets/icons/ProfileX.jsx
  src/components/Profile/index.jsx
  src/components/Profile/styles.module.scss
  src/pages/TestPage/index.jsx
  src/styles/index.scss
  src/styles/styles.css
Labels: ✨ Feat

#12 ✨ Feat: 모달 컴포넌트 구현
  src/assets/icons/BackButton.jsx
  src/assets/icons/ModalCloseButton.jsx
  src/components/Modal/components/ModalHeader/index.jsx
  src/components/Modal/components/ModalHeader/styles.module.scss
  src/components/Modal/components/ModalMobileHeader/index.jsx
  src/components/Modal/components/ModalMobileHeader/styles.module.scss
  src/components/Modal/index.jsx
  src/components/Modal/styles.module.scss
  src/hooks/useModal.js
  src/pages/TestPage/index.jsx
Labels: ✨ Feat

#16 ✨ Feat: 헤더 구현
  src/assets/icons/Logo.jsx
  src/assets/images/user_icon.png
  src/components/Header/index.jsx
  src/components/Header/styles.module.scss
  src/pages/TestPage/index.jsx
Labels: ✨ Feat

#26 🔨 Refactor: 프로필 사진 컴포넌트 리팩토링
  .eslintrc.cjs
  src/components/Modal/index.jsx
  src/components/Profile/index.jsx
  src/components/Profile/styles.module.scss
  src/pages/TestPage/index.jsx
Labels: 🔨 Refactor

#11 ✨ Feat: 진행바 컴포넌트 구현
  .eslintrc.cjs
  package-lock.json
  src/assets/icons/Credit.jsx
  src/pages/ListPage/components/ProgressBar/index.jsx
  src/pages/ListPage/components/ProgressBar/styles.module.scss
  src/pages/TestPage/index.jsx
  src/utils/getTimeLeft.js
  src/utils/numberWithCommas.js
Labels: ✨ Feat

#9 ✨ Feat: 캐러셀 컴포넌트 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  src/assets/icons/Arrow.jsx
  src/components/Carousel/index.jsx
  src/components/Carousel/styles.module.scss
  src/components/Header/styles.module.scss
  src/components/Profile/index.jsx
  src/constants/carouselSetting.js
  src/constants/constants.js
  src/constants/screenSizes.js
  src/pages/TestPage/index.jsx
  src/pages/TestPage/styles.module.scss
  src/styles/normalize.scss
Labels: ✨ Feat

#30 🐛 Fix: 패키지 재설치
  build.sh
  package-lock.json
  src/pages/TestPage/index.jsx
  vercel.json
Labels: 📦️ Chore, 🐛 Fix

#32 📦️ Chore: 자동 배포 Github Action 작성
  .github/workflows/deploy.yml
Labels: 📦️ Chore

#24 ✨ Feat: CustomButton 컴포넌트 구현
  src/components/CustomButton/index.jsx
  src/components/CustomButton/styles.module.scss
  src/pages/TestPage/index.jsx
  src/styles/color.scss
  src/styles/font.scss
Labels: ✨ Feat

#35 📦️ Chore: Pull Request 시 vercel 자동배포 구현
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .gitignore
  src/components/Profile/styles.module.scss
  src/pages/TestPage/index.jsx
Labels: ✨ Feat, 📦️ Chore

#28 🔨 Refactor: 모달 컴포넌트 리팩토링
  src/components/Modal/components/ModalHeader/index.jsx
  src/components/Modal/components/ModalHeader/styles.module.scss
  src/components/Modal/components/ModalMobileHeader/index.jsx
  src/components/Modal/components/ModalMobileHeader/styles.module.scss
  src/components/Modal/index.jsx
  src/components/Modal/styles.module.scss
  src/pages/MyPage/styles.module.scss
  src/styles/font.scss
Labels: 🔨 Refactor

#40 ✨ Feat: 모달 애니메이션 적용
  package-lock.json
  package.json
  src/components/Modal/index.jsx
Labels: ✨ Feat

#41 ✨Feat: 이달의 컴포넌트 UI 구현
  src/assets/icons/Chart.jsx
  src/hooks/useSetNumberOfItemsToShow.js
  src/pages/ListPage/Credit/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/ChartElement/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartElement/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/Tab/index.jsx
  src/pages/ListPage/MonthlyChart/components/Tab/styles.module.scss
  src/pages/ListPage/MonthlyChart/index.jsx
  src/pages/ListPage/MonthlyChart/mock.js
  src/pages/ListPage/MonthlyChart/styles.module.scss
  src/pages/ListPage/index.jsx
  src/pages/ListPage/styles.module.scss
  src/pages/TestPage/index.jsx
  src/utils/utils.js
Labels: ✨ Feat

#50 ✨ Feat: NotFound 페이지 구현
  src/assets/images/aespa.jpg
  src/assets/images/nctdream.jpg
  src/assets/images/newjeans.jpg
  src/assets/images/seventeen.jpg
  src/pages/NotFoundPage/index.jsx
  src/pages/NotFoundPage/styles.module.scss
  src/router.jsx
Labels: ✨ Feat

#48 ✨ Feat: 로딩에러 컴포넌트 구현
  src/components/LoadingError/index.jsx
  src/components/LoadingError/styles.module.scss
  src/pages/ListPage/MonthlyChart/index.jsx
  src/pages/TestPage/index.jsx
Labels: ✨ Feat

#55 ✨ Feat: framer-motion 사용하여 애니메이션 적용
  src/components/CustomButton/index.jsx
  src/pages/ListPage/Credit/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartElement/index.jsx
Labels: ✨ Feat

#58 ✨ Feat: 로딩 스피너
  src/assets/icons/Spinner.jsx
  src/pages/ListPage/MonthlyChart/index.jsx
  src/pages/ListPage/MonthlyChart/styles.module.scss
  src/pages/TestPage/index.jsx
Labels: ✨ Feat

#60 🔨 Refactor: 모달 Portal 을 사용하여 구현
  src/components/Modal/index.jsx
Labels: 🔨 Refactor, 🐛 Fix

#51 ✨ Feat: 마이 페이지 컴포넌트 UI 구현
  .gitignore
  package-lock.json
  src/api/getIdolData.js
  src/api/index.js
  src/assets/icons/Plus.jsx
  src/constants/carouselSetting.js
  src/pages/ListPage/Donation/components/Card/styles.module.scss
  src/pages/ListPage/Donation/styles.module.scss
  src/pages/MyPage/components/IdolFavoriteList/carouselSettings.js
  src/pages/MyPage/components/IdolFavoriteList/index.jsx
  src/pages/MyPage/components/IdolFavoriteList/styles.module.scss
  src/pages/MyPage/components/IdolSelectList/carouselSettings.js
  src/pages/MyPage/components/IdolSelectList/index.jsx
  src/pages/MyPage/components/IdolSelectList/styles.module.scss
  src/pages/MyPage/components/Nothing/index.jsx
  src/pages/MyPage/components/Nothing/styles.module.scss
  src/pages/MyPage/index.jsx
  src/pages/MyPage/mock.json
  src/pages/MyPage/styles.module.scss
  src/pages/TestPage/index.jsx
  src/pages/TestPage/mock.json
  src/styles/color.scss
  src/utils/localStorage.js
  src/utils/sortItems.js
  src/utils/splitItems.js
  vite.config.js
Labels: ✨ Feat

#45 ✨ Feat: 후원을 기다리는 조공 API 기능 구현
  src/apis/api.js
  src/apis/getDonations.js
  src/constants/endpoint.js
  src/constants/errorMessage.js
  src/hooks/useLoad.js
  src/pages/ListPage/Credit/styles.module.scss
  src/pages/ListPage/Donation/components/Card/styles.module.scss
  src/pages/ListPage/Donation/index.jsx
  src/pages/ListPage/Donation/mock.json
  src/pages/ListPage/Donation/styles.module.scss
Labels: ✨ Feat

#63 ✨ Feat: 크레딧 충전, 후원하기, 투표하기 Modal UI 및 로컬 스토리지 기능 구현
  package-lock.json
  package.json
  src/components/CustomButton/index.jsx
  src/components/Modal/styles.module.scss
  src/constants/credit.js
  src/contexts/CreditContext.jsx
  src/main.jsx
  src/pages/ListPage/Credit/CreditModal.jsx
  src/pages/ListPage/Credit/index.jsx
  src/pages/ListPage/Credit/modal.module.scss
  src/pages/ListPage/Donation/components/Card/DonationModal.jsx
  src/pages/ListPage/Donation/components/Card/index.jsx
  src/pages/ListPage/Donation/components/Card/modal.module.scss
  src/pages/ListPage/MonthlyChart/ChartModal.jsx
  src/pages/ListPage/MonthlyChart/index.jsx
  src/pages/ListPage/MonthlyChart/mock.js
  src/pages/ListPage/MonthlyChart/modal.module.scss
  src/pages/MyPage/components/IdolSelectList/carouselSettings.js
  src/router.jsx
  src/utils/input.js
  src/utils/localStorage.js
Labels: ✨ Feat

#46 ✨ Feat: 이달의 차트 기능 구현
  src/api/index.js
  src/apis/getCharts.js
  src/apis/getIdolData.js
  src/components/CustomButton/index.jsx
  src/constants/tabTypes.js
  src/hooks/useSetNumberOfItemsToShow.js
  src/pages/ListPage/Credit/components/CreditModal/index.jsx
  src/pages/ListPage/Credit/components/CreditModal/styles.module.scss
  src/pages/ListPage/Credit/index.jsx
  src/pages/ListPage/Donation/components/Card/index.jsx
  src/pages/ListPage/Donation/components/DonationModal/index.jsx
  src/pages/ListPage/Donation/components/DonationModal/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/ChartElement/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartElement/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/ChartModal/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartModal/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/IdolChart/index.jsx
  src/pages/ListPage/MonthlyChart/components/IdolChart/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/MoreButton/index.jsx
  src/pages/ListPage/MonthlyChart/components/MoreButton/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/Tab/index.jsx
  src/pages/ListPage/MonthlyChart/components/Tab/styles.module.scss
  src/pages/ListPage/MonthlyChart/index.jsx
  src/pages/ListPage/MonthlyChart/mock.js
  src/pages/ListPage/MonthlyChart/styles.module.scss
  src/styles/color.scss
Labels: ✨ Feat

#69 🐛 Fix: 디자인 수정 및 랭킹 index 로 변경
  src/assets/images/github.png
  src/components/Carousel/styles.module.scss
  src/components/Footer/index.jsx
  src/components/Footer/styles.module.scss
  src/pages/ListPage/Credit/styles.module.scss
  src/pages/ListPage/Donation/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartElement/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartModal/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartModal/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/IdolChart/index.jsx
  src/pages/ListPage/index.jsx
  src/pages/ListPage/styles.module.scss
  src/pages/MyPage/index.jsx
  src/pages/MyPage/styles.module.scss
  src/styles/font.scss
Labels: 🐛 Fix

#67 ✨ Feat: 모달 API 기능 구현
  src/apis/postVotes.js
  src/apis/putContribute.js
  src/constants/errorMessage.js
  src/pages/ListPage/Donation/components/Card/index.jsx
  src/pages/ListPage/Donation/components/DonationModal/index.jsx
  src/pages/ListPage/Donation/components/DonationModal/styles.module.scss
  src/pages/ListPage/Donation/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartModal/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartModal/styles.module.scss
  src/pages/ListPage/MonthlyChart/index.jsx
Labels: ✨ Feat

#72 🔨 Refactor: 후원하기 모달 GET 재요청 코드 수정
  src/pages/ListPage/Donation/index.jsx
Labels: 🔨 Refactor, 🐛 Fix

#78 ✨ Feat: 랜딩 페이지 애니메이션 적용
  src/pages/LandingPage/components/index.jsx
  src/pages/LandingPage/index.jsx
Labels: ✨ Feat

#82 🐛 Fix: 스크롤 오류 수정
  src/hooks/useScrollToTop.js
  src/pages/LandingPage/index.jsx
  src/pages/LandingPage/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/ChartModal/index.jsx
  src/pages/ListPage/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/NotFoundPage/index.jsx
Labels: 🐛 Fix

#56 ✨ Feat: 그라디언트 컴포넌트 UI 생성
  src/App.jsx
  src/assets/icons/Gradient.jsx
  src/components/Background/index.jsx
  src/components/Background/styles.module.scss
  src/components/Modal/styles.module.scss
  src/main.jsx
  src/pages/ListPage/index.jsx
  src/pages/ListPage/styles.module.scss
  src/pages/MyPage/components/IdolFavoriteList/styles.module.scss
  src/pages/MyPage/index.jsx
  src/pages/MyPage/styles.module.scss
  src/pages/NotFoundPage/styles.module.scss
  src/router.jsx
Labels: ✨ Feat

#84 ✨ Feat: 애니메이션 적용
  src/App.jsx
  src/components/Modal/index.jsx
  src/pages/LandingPage/index.jsx
  src/pages/ListPage/index.jsx
  src/pages/MyPage/index.jsx
  src/router.jsx
Labels: ✨ Feat

#91 ✨Feat: 스크롤바 커스텀
  src/styles/normalize.scss
Labels: ✨ Feat

#89 README 파일 수정
  README.md
Labels: 📚 Docs

#92 🔨 Refactor: 코드 리팩토링
  src/App.jsx
  src/apis/index.js
  src/assets/icons/BackButton.jsx
  src/assets/icons/Chart.jsx
  src/assets/icons/Check.jsx
  src/assets/icons/Credit.jsx
  src/assets/icons/Gradient.jsx
  src/assets/icons/ModalCloseButton.jsx
  src/assets/icons/ProfileX.jsx
  src/assets/icons/Spinner.jsx
  src/components/Carousel/index.jsx
  src/components/Carousel/styles.module.scss
  src/components/CustomButton/index.jsx
  src/components/Footer/index.jsx
  src/components/Header/index.jsx
  src/components/Header/styles.module.scss
  src/components/Modal/components/ModalHeader/index.jsx
  src/components/Modal/components/ModalHeader/styles.module.scss
  src/components/Modal/components/ModalMobileHeader/index.jsx
  src/components/Modal/components/ModalMobileHeader/styles.module.scss
  src/components/Modal/index.jsx
  src/components/Modal/styles.module.scss
  src/components/Sample/Sample.jsx
  src/hooks/hook.js
  src/hooks/useTitle.js
  src/main.jsx
  src/pages/LandingPage/index.jsx
  src/pages/LandingPage/styles.module.scss
  src/pages/ListPage/Credit/index.jsx
  src/pages/ListPage/Credit/styles.module.scss
  src/pages/ListPage/Donation/components/Card/index.jsx
  src/pages/ListPage/Donation/components/Card/styles.module.scss
  src/pages/ListPage/Donation/components/ProgressBar/index.jsx
  src/pages/ListPage/Donation/components/ProgressBar/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/ChartElement/index.jsx
  src/pages/ListPage/MonthlyChart/components/ChartElement/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/IdolChart/styles.module.scss
  src/pages/ListPage/MonthlyChart/components/MoreButton/index.jsx
  src/pages/ListPage/MonthlyChart/components/MoreButton/styles.module.scss
  src/pages/ListPage/MonthlyChart/styles.module.scss
  src/pages/ListPage/styles.module.scss
  src/pages/MyPage/components/IdolFavoriteList/index.jsx
  src/pages/MyPage/components/IdolFavoriteList/styles.module.scss
  src/pages/MyPage/components/IdolSelectList/index.jsx
  src/pages/MyPage/components/IdolSelectList/styles.module.scss
  src/pages/MyPage/components/Nothing/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/NotFoundPage/styles.module.scss
  src/pages/TestPage/index.jsx
  src/pages/TestPage/styles.module.scss
  src/router.jsx
  src/utils/debounce.js
  src/utils/getTimeLeft.js
  src/utils/numberWithCommas.js
  src/utils/sortItems.js
  src/utils/splitItems.js
  src/utils/utils.js
Labels: 🔨 Refactor

#94 ♻️ Refactor: README 파일 일부 수정
  README.md
Labels: 📚 Docs
